### ISSUE TITLE
Cheatbreaker Deobf 

### ISSUE THREAD

**Issue by BotMertCool** [narumii/Deobfuscator#17]
Cheatbreaker's Obfuscator is free to use and open source
https://github.com/CheatBreaker/Obf

it would be cool if you added a deobfuscator for it.
However, I understand if you do not want too lol.

**Comment by NathanKassab** [comment]
why does the repo's description say "sorry cheatengine"?

**Comment by Python-22** [comment]
none of the string seem to actually be encrypted, so if you run this transformer [UniversalNumberTransformer](https://github.com/narumii/Deobfuscator/blob/master/src/main/java/uwu/narumi/deobfuscator/transformer/impl/universal/other/UniversalNumberTransformer.java) it should clear up the number obfuscation and then you should be able to see where the string is in the array

example:
![image](https://user-images.githubusercontent.com/73321240/149856740-530caa05-7968-4182-b694-ba41f18d8d56.png)

**Comment by SolarisAVR** [comment]
how do you even manage to make it work lmfao

**Comment by narumii** [comment]
Done
