### ISSUE TITLE
ImageCrasherRemoveTransformer typo

### ISSUE THREAD

**Issue by Diazole** [narumii/Deobfuscator#25]
The transform func in ImageCrasherRemoveTransformer should call `getFiles()` and `getClasses()`

https://github.com/narumii/Deobfuscator/blob/9d27dfc2ef427d6c3e0347f719dc7e3ffbea650d/src/main/java/uwu/narumi/deobfuscator/transformer/impl/universal/remove/ImageCrasherRemoveTransformer.java#L9-L12

**Comment by narumii** [comment]
Fuck me i fucked up
