### ISSUE TITLE
qProtect deobfuscator broken

### ISSUE THREAD

**Issue by xBrownieCodezV2** [narumii/Deobfuscator#26]
Insane deobf working 100% on 1.7.2
https://img.mdma.dev/bvrg8Zk.png

**Comment by narumii** [comment]
Dziekujemy za zgloszenie, niestety nie jestesmy nic w stanie poradzic na twoje spierdolenie wiec prosze wypierdalac. Jesli potrzebujesz wiecej informacji to deobfuscator nie posiada transformerow na najnowsa wersje twojego zjebanego obf.
