### ISSUE TITLE
Plz add transformers for new bozar 1.7.0 

### ISSUE THREAD

**Issue by JabaSkidCode** [narumii/Deobfuscator#30]
Can u add new transformers? https://github.com/vimasig/Bozar, codders need new source! 
https://workupload.com/file/83tYVpNwWTX example, and add to discord channel to examples jar url, because many peoples no have a nitro

**Comment by noom1337** [comment]
> codders need new source!
maybe skids, not "codders"?

**Comment by NathanKassab** [comment]
Excuse my language, but what the fuck are you trying to say?

**Comment by narumii** [comment]
Probably that skids need bozar deobfuscator because of plugins using it and they cant skid

**Comment by narumii** [comment]
👍🏻
