### ISSUE TITLE
Caesium transformer is not working on "Wack" dictionary

### ISSUE THREAD

**Issue by Jakubk15** [narumii/Deobfuscator#32]
The caesium transformer is not working on "Wack" dictionary. It seems to change something in the JAR file, but it is still far from readable. Can someone have a look at that?

**Comment by narumii** [comment]
https://github.com/sim0n/Caesium/blob/305dd505c938ca7b65d5491fb7aac867b68dcfdf/src/main/java/dev/sim0n/caesium/util/Dictionary.java#L8

https://github.com/sim0n/Caesium/blob/305dd505c938ca7b65d5491fb7aac867b68dcfdf/src/main/java/dev/sim0n/caesium/mutator/ClassMutator.java#L32
