### ISSUE TITLE
Full caesium support

### ISSUE THREAD

**Issue by gooses1337** [narumii/Deobfuscator#38]
Hello, can you add full support caesium? deobfuscating at minimum settings is not decrypt, please fix that.

**Comment by narumii** [comment]
So what is wrong with caesium transformers exactly?

**Comment by gooses1337** [comment]
Caesium cant deobfuscate full code, i can send example jar file to your discord server, and we can deobfuscate it together, I will show you the incomplete decoding

**Comment by HeyaGlitz** [comment]
Exactly which transformer doesn't work?

**Comment by gooses1337** [comment]
with caesium transformer .-.

**Comment by HeyaGlitz** [comment]
💀

**Comment by narumii** [comment]
So maybe i will ask different: What isn't deobfuscated by transformers, what obfuscation is left in jar?
Or send sample

**Comment by uwuplant** [comment]
if the person creating the issue is who I think it is, then they're most likely referring to caesium using wacky dictionary

**Comment by 0x343a** [comment]
Did you tried change the dictionary?

**Comment by narumii** [comment]
Ngl i don't even know wtf happened
Changing dictionary causes transformers to stop working properly i think

**Comment by narumii** [comment]
Yeah i'm dumb af

**Comment by gooses1337** [comment]
fix transformers please))
