### ISSUE TITLE
[FR] Remove useless if statements

### ISSUE THREAD

**Issue by KTibow** [narumii/Deobfuscator#39]
I had a obfuscated piece of malware that had a lot of statements like
```java
if (true) {
```
or
```java
if (-1 != 0) {
```
or
```java
if (-1 == -1) {
```
If anyone had some spare time, it would be nice to implement a transformer to remove them.

**Comment by narumii** [comment]
https://github.com/narumii/Deobfuscator/blob/master/src/main/java/uwu/narumi/deobfuscator/transformer/impl/sb27/SuperblaubeereFlowTransformer.java

**Comment by KTibow** [comment]
well i just wasted a lot of time working on regexes to use on decompiled code but thanks i guess
