### ISSUE TITLE
Binscure 0.4 crack deobfuscation transformer request + Cracked Jar Download

### ISSUE THREAD

**Issue by Integer-Obf** [narumii/Deobfuscator#4]
Hey! 
There is a very old version of Binscure that some skids still leach off of this pirated build, I was wondering If you could possibly make a transformer or got any tutorials for asm that I can learn to make my own transformer (That would be helpful) Thanks!
(yes i removed link i forgot about it ~narumii)

**Comment by narumii** [comment]
InvokeDynamic/Indirection transformer doesn't work for me also i completed transformers in 80% i think

**Comment by narumii** [comment]
i think is done i didn't create full flow transformer but i think code is readable

**Comment by RealNoahgg** [comment]
> InvokeDynamic/Indirection

So does it work now? on Binscure 0.4
