### ISSUE TITLE
qprotect deobfuscated

### ISSUE THREAD

**Issue by xBrownieCodezV2** [narumii/Deobfuscator#43]
https://media.discordapp.net/attachments/948736279179304989/1001520709039820860/ezgif-2-a7beef4a24.gif

**Comment by narumii** [comment]
https://user-images.githubusercontent.com/57463654/183216593-b0685c5c-4bd1-43f0-ae48-e861b0a4644c.mp4

**Comment by thehydrogen** [comment]
qprotect deobfuscated $$

**Comment by AdvancedAntiSkid** [comment]
qprotect deobfuscated
