### ISSUE TITLE
MathHelper typo

### ISSUE THREAD

**Issue by ShadowNullWow** [narumii/Deobfuscator#57]
I got wrong results when I was using UniversalNumberTransformer, and I checked the code in MathHelper.
https://github.com/narumii/Deobfuscator/blob/96666b863330e67d3039eb9055f1c7424c61c6c8/src/main/java/uwu/narumi/deobfuscator/helper/MathHelper.java#L22-L23
https://github.com/narumii/Deobfuscator/blob/96666b863330e67d3039eb9055f1c7424c61c6c8/src/main/java/uwu/narumi/deobfuscator/helper/MathHelper.java#L53-L54
`opcode` should be`second`

**Comment by narumii** [comment]
Im suprised this was't seen until now
