### ISSUE TITLE
TryCatchFixTransformer improperly delete Try Catch Blocks

### ISSUE THREAD

**Issue by ShadowNullWow** [narumii/Deobfuscator#60]
https://github.com/narumii/Deobfuscator/blob/c865042c18d657ecc6b0a3363fbb5784e529c4a9/src/main/java/uwu/narumi/deobfuscator/transformer/impl/universal/other/TryCatchFixTransformer.java#L19

This condition is incorrect.
`tbce.end.equals(tbce.handler)`

e.g.
TCB:start Label1 end Label2 handler Label2
**// the beginning**
Label1
...do sth
GOTO Label3
**// the end**
Label2
...For handler
Label3
... do sth

In this case, the try catch block will be improperly deleted.

**Comment by narumii** [comment]
addressed in the new version
